apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-demonset
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
      - name: bach-containers
        image: busybox
        command: ["echo", "Hello, Kubernetes! This is a Job running a one-time task."]
      restartPolicy: Never
  
